name: craft-blockchain
version: "${project.version}"
author: Reecepbcups
main: com.crafteconomy.blockchain.CraftBlockchainPlugin
description: Blockchain integration for Craft Economy
api-version: 1.17
# Redis & MongoDB
database: true

commands:
  wallet:
    description: crafteconomy wallet integration command
    usage: /<command>
    aliases: [craftwallet, cwallet]